resources:
  - name: repo_matrix_dynamic_steplets_debug
    type: GitRepo
    configuration:
      gitProvider: manishas_jfrog_github
      path: manishas-jfrog/matrix-dynamic-steplets
      branches:
        include: "^debug$"

pipelines:
  - name: Matrix_Dynamic_Steplets
    steps:
      - name: pre_matrix
        type: PreMatrix
        configuration:
          inputResources:
            - name: repo_matrix_dynamic_steplets_debug
        execution:
          onExecute:
            - compare_results=$(compare_git --resource repo_matrix_dynamic_steplets_debug)
            - if grep -q "steplet1.txt" <<< $compare_results; then echo "steplet1.txt was changed"; fi
            - if grep -q "steplet1.txt" <<< $compare_results; then steplet1=true; fi
            - if grep -q "steplet2.txt" <<< $compare_results; then echo "steplet2.txt was changed"; fi
            - if grep -q "steplet2.txt" <<< $compare_results; then steplet2=true; fi
            - if grep -q "steplet3.txt" <<< $compare_results; then echo "steplet3.txt was changed"; fi
            - if grep -q "steplet3.txt" <<< $compare_results; then steplet3=true; fi
            - if grep -q "steplet4.txt" <<< $compare_results; then echo "steplet4.txt was changed"; fi
            - if grep -q "steplet4.txt" <<< $compare_results; then steplet4=true; fi
            - set_step_var matrix_envs "steplet1 = ${steplet1},steplet2 = ${steplet2},steplet3 = ${steplet3},steplet4 = ${steplet4}"

      - name: matrix_example
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps:
            - name: pre_matrix
        stepletMultipliers:
          environmentVariables:
            - steplet: 1
            - steplet: 2
            - steplet: 3
            - steplet: 4    
        execution:
          onExecute:
            - get_step_var pre_matrix matrix_envs
            - echo $steplet1
            - echo $steplet2
            - echo $steplet3
            - echo $steplet4
            - if [ $steplet1 ]; then echo "Execute steplet1"; else echo "Not executing steplet1"; fi 
            - if [ $steplet2 ]; then echo "Execute steplet2"; else echo "Not executing steplet2"; fi 
            - if [ $steplet3 ]; then echo "Execute steplet3"; else echo "Not executing steplet3"; fi 
            - if [ $steplet4 ]; then echo "Execute steplet4"; else echo "Not executing steplet4"; fi 
